from __future__ import annotations

from typing import Any, Protocol

from ..workflow.models import ExecutionContext


class CapabilityHandler(Protocol):
    def __call__(self, typed_input: dict[str, Any], execution_context: ExecutionContext) -> dict[str, Any]: ...


class MapAdapter(Protocol):
    def capabilities(self) -> set[str]: ...
    def compile(self, request: dict[str, Any]) -> dict[str, Any]: ...
    def render(self, request: dict[str, Any]) -> dict[str, Any]: ...


class RendererAdapter(Protocol):
    def capabilities(self) -> set[str]: ...
    def compile_scene(self, request: dict[str, Any]) -> dict[str, Any]: ...
    def submit_render(self, session_id: str, scene: dict[str, Any], renderer_id: str, frontend_build: str) -> dict[str, Any]: ...
    def validate_receipt(self, receipt: dict[str, Any], expected_scene_digest: str) -> None: ...
